name: movie_marks
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  flutter_svg: ^2.0.0
  http: ^0.13.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.0
  shared_preferences: ^2.3.2
  bloc: ^8.1.0
  dio: ^5.0.0
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5
  flashy_tab_bar2: ^0.0.10
  cupertino_icons: ^1.0.8
  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700