class AppConstants {
  static const appName = "Movie Marks";
  static const home = "Home";
  static const watchList = "Watch List";
  static const settings = "Settings";
  static const welcomeBack = "Welcome Back!";
  static const overViews = "Overviews";
  static const releaseDate = "Release Date";
  static const popularity = "Popularity";
  static const title = "Title";
  static const averageRating = "Average Rating";
  static const readMore = "Read More";
  static const rateCount = "Rate Count";
  static const genreTitle = "Categories";
  static const emptyMovie = "No movies found.";
  static const overview = "Overviews";
  static const reviews = "Reviews";
  static const casts = "Casts";
  static const crew = "Crews";
  static const productionCompany = "Production Company";
  static const productionCompanies = "Production Companies";
  static const productionCountry = "Production Country";
  static const productionCountries = "Production Countries";
  static const originalTitle = "Original Title";
  static const originalLanguage = "Original Language";
  static const keywords = "Keywords";
  static const socialNetwork = "Social Network";
  static const unKnow = "Unknown";
}
